### PR TITLE
FireFox Bug

### PR DESCRIPTION
**Pull request by naduda**
In the FireFox:
var svg = document.getElementsByTagName('svg')[0];
console.log('Result = ' + svg.offsetHeight); 

//Result = NaN, but offsetHeight for div element is number.
//This solve issuse for FireFox

### CODE REVIEW

**Comment by davidpfahler** [comment]
@naduda Hi and thank you for your feedback. I understand that you have a problem with Firefox and SVG elements. I still have the following questions:
1. Can you please specify what version of Firefox you were testing? 
2. Can you please specify what you tried to do with an SVG element related to iScroll?
3. Can you please specify the expected behaviour of using SVG and iScroll? 
4. Can you please specify the actual, broken behaviour of using SVG and iScroll?

Also, please note that you made changes to the `build/iscroll-zoom` file, but we would need to make changes to the source files.

**Comment by naduda** [comment]
Hi, David.
I speak English some bad, but I try explain following questions...
I have English lessons two days at week :), and I happy to answer.

1. Can you please specify what version of Firefox you were testing? The
latest one - yesterday downloaded )))
2,3,4 - if You will be have a some free time tomorow (or later) call
(write) me in skype and I will give you a link to my app (I start it (app)
in own laptop). Maybe You have now free time then call me back right now.
My skype - naduda.pr (the dark photo - I in blue jacket, and location
Ukraine)

Why did you comment out this.translateZ? Because I have not clear picture
(fog) in browser when I use this library.


2015-05-20 15:28 GMT+03:00 David Pfahler <notifications@github.com>:

**Comment by naduda** [comment]
My wife speaks Italian very well. If you are Italian we can speak in your
language.

>
>

**Comment by davidpfahler** [comment]
@naduda I understand you have a problem with iScroll, but this is an open source project and iScroll has over 300 open issues. If you cannot supply the information so I can help you with your project here, I'm afraid I cannot proceed. When you can post answers to the questions above, I will reopen the issue.

**Pull request closed without merging**
